<?php

$skinData = array(
    'elements_enhanced_by_borders' => array(
       'hero_avatar'          => 'background',
       'hero_body'            => 'background',
       'block_body'           => 'background',
    ),

    'options' => array(
       'paginator_template'   => 'BNB',
       'clickanchor_template' => '',
       'top_banner_position'  => 'top_of_page',
       'fixed_left_col_width' => 0,
       'fixed_left_col_top'   => 0,
       'fixed_top_row_height' => 0,
       'main_menu_upper_case' => 1,
       'top_banner_in_table'  => 1,
    ),

    'borders' => array(
       'normal'        => array(
               '0'             => 'background',
               '1'             => 'border-left',
               '2'             => 'border-top',
               '3'             => 'border-right',
               '4'             => 'border-bottom',
               '5'             => 'border-top-left',
               '6'             => 'border-top-right',
               '7'             => 'border-bottom-left',
               '8'             => 'border-bottom-right',
       ),
       'background'    => array(
               '0'             => 'background',
               '1'             => 'border-top',
               '2'             => 'border-bottom',
       ),
    ),

    'render_fonts' => array(
       '0'                    => 'font_Hero_Name',
       '1'                    => 'font_Hero_Title',
       '2'                    => 'font_Hero_Class',
       '3'                    => 'font_Hero_Race',
       '4'                    => 'font_Hero_Level',
       '5'                    => 'font_menu-1',
       '6'                    => 'font_menu-1-selected',
       '7'                    => 'font_menu-1-hovered',
    ),

    'props' => array(
       'space-top'     => array(
               'layout'        => 'top',
               'height'        => 20,
       ),
       'logo'          => array(
               'layout'        => 'top',
               'height'        => 50,
               'width_type'    => 'auto',
               'inline'        => 'true',
               'sort_index'    => 1,
       ),
       'worlds'        => array(
               'layout'        => 'top',
               'sort_index'    => 2,
               'inline'        => 'true',
               'movable'       => 'true',
               'halignment'    => 'left',
               'type'          => 'worlds',
               'hideable'      => 'true',
       ),
       'diamonds'      => array(
               'layout'        => 'top',
               'inline'        => 'true',
               'sort_index'    => 4,
               'halignment'    => 'right',
               'movable'       => 'true',
               'type'          => 'diamonds',
               'hideable'      => 'true',
               'show_admin'    => 'false',
       ),
       'tombola'         => array(
               'layout'        => 'top',
               'inline'        => 'true',
               'sort_index'    => 5,
               'halignment'    => 'right',
               'movable'       => 'true',
               'width_type'    => 'auto',
               'type'          => 'tombola',
               'hideable'      => 'true',
               'show_admin'    => 'false',
       ),
       'clock'         => array(
               'layout'        => 'top',
               'inline'        => 'true',
               'sort_index'    => 5,
               'halignment'    => 'right',
               'movable'       => 'true',
               'width_type'    => 'auto',
               'type'          => 'clock',
               'hideable'      => 'true',
               'show_admin'    => 'false',
       ),
       'buttons'       => array(
               'layout'        => 'top',
               'sort_index'    => 6,
               'halignment'    => 'right',
               'width'         => 250,
               'type'          => 'buttons',
               'movable'       => 'true',
               'hideable'      => 'false',
               'show_admin'    => 'false',
               'allow_linebreak' => 'false',
       ),
       'space-right'   => array(
               'layout'        => 'right',
               'hidden'        => 'false',
               'sort_index'    => 1,
       ),
       'hero'          => array(
               'layout'        => 'right',
               'sort_index'    => 2,
               'fame_ep_has_numbers' => 'false',
               'dont_merge'    => 'true',
               'type'          => 'hero',
               'movable'       => 'true',
               'hideable'      => 'true',
               'show_admin'    => 'false',
               'allow_linebreak' => 'true',
       ),
       'group'         => array(
               'layout'        => 'right',
               'sort_index'    => 3,
               'type'          => 'group',
               'movable'       => 'left-right',
               'hideable'      => 'true',
               'show_admin'    => 'false',
               'width_type'    => 'auto',
       ),
       'groupmsg'      => array(
               'layout'        => 'right',
               'type'          => 'groupmsg',
               'movable'       => 'left-right',
               'hideable'      => 'true',
               'show_admin'    => 'false',
               'width_type'    => 'auto',
       ),
       'nextdungeon'      => array(
               'layout'        => 'right',
               'type'          => 'nextdungeon',
               'movable'       => 'left-right',
               'hideable'      => 'true',
               'show_admin'    => 'false',
               'width_type'    => 'auto',
       ),
       'chat'          => array(
               'type'          => 'chat',
               'movable'       => 'true',
               'hideable'      => 'true',
               'show_admin'    => 'false',
               'layout'        => 'right',
               'height'        => 300,
               'height_enabled' => 'true',
       ),
       'medals'        => array(
               'layout'        => 'right',
               'sort_index'    => 4,
               'movable'       => 'left-right',
               'hidden'        => 0,
               'height'        => 170,
               'type'          => 'medals',
               'hideable'      => 'true',
               'show_admin'    => 'false',
               'width_type'    => 'auto',
       ),
       'space-left'    => array(
               'layout'        => 'left',
               'sort_index'    => 1,
               'width'         => 100,
       ),
       'languages'     => array(
               'layout'        => 'left',
               'sort_index'    => 3,
               'movable'       => 'true',
               'type'          => 'languages',
       ),
       'menu'          => array(
               'layout'        => 'left',
               'width'         => 120,
               'width_type'    => 'minimal',
               'width_enabled' => 'true',
               'sort_index'    => 4,
               'height'        => 0,
               'min-height'    => 300,
               'type'          => 'menu',
               'movable'       => 'false',
               'hideable'      => 'false',
       ),
       'ticker'        => array(
               'layout'        => 'center',
               'sort_index'    => 5,
               'halignment'    => 'center',
               'height'        => 20,
               'height_enabled' => 'true',
               'type'          => 'ticker',
               'movable'       => 'true',
               'hideable'      => 'true',
               'show_admin'    => 'false',
               'delay'         => 6,
               'allow_linebreak' => 'true',
       ),
       'main_content'  => array(
               'layout'        => 'center',
               'fill_height'   => 'true',
               'sort_index'    => 7,
               'table_border'  => 'true',
               'height'        => 0,
               'min-height'    => 400,
               'type'          => 'content',
               'movable'       => 'false',
               'hideable'      => 'false',
               'clear_inline'  => 'true',
       ),
       'footer'        => array(
               'type'          => 'footer',
               'layout'        => 'center',
               'sort_index'    => 8,
               'halignment'    => 'center',
       ),
       'server_status' => array(
               'type'          => 'server_status',
       ),

    ),

);


?>
